#!/bin/bash
for x in `find /usr/share/nginx/html/js -type f -iname '*.js'`
do
    /usr/bin/zopfli  -i40 ${x} 
done

for x in `find /usr/share/nginx/html/css -type f -iname '*.css'`
do

        /usr/bin/zopfli -i40 ${x}
done

